import type { Config } from "tailwindcss";

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
        heading: ["var(--font-heading)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        display: ["var(--font-heading)", "system-ui", "sans-serif"],
        label: ["var(--font-label)", "system-ui", "sans-serif"],
      },
      colors: {
        void: "#0C1330",
        "bone-white": "#ffffff",
        "ash-gray": "#9a9a9a",
        "silver-mist": "#bdbdbd",
        coral: "#FF5A1F",
        "coral-dim": "#ff5a1f80",
        "deep-navy": "#0C1330",
        "navy-light": "#1a2342",
        background: {
          50: "oklch(var(--background-50) / <alpha-value>)",
          100: "oklch(var(--background-100) / <alpha-value>)",
          200: "oklch(var(--background-200) / <alpha-value>)",
          300: "oklch(var(--background-300) / <alpha-value>)",
          400: "oklch(var(--background-400) / <alpha-value>)",
          500: "oklch(var(--background-500) / <alpha-value>)",
          600: "oklch(var(--background-600) / <alpha-value>)",
          700: "oklch(var(--background-700) / <alpha-value>)",
          800: "oklch(var(--background-800) / <alpha-value>)",
          900: "oklch(var(--background-900) / <alpha-value>)",
          950: "oklch(var(--background-950) / <alpha-value>)",
        },
        primary: {
          50: "oklch(var(--primary-50) / <alpha-value>)",
          100: "oklch(var(--primary-100) / <alpha-value>)",
          200: "oklch(var(--primary-200) / <alpha-value>)",
          300: "oklch(var(--primary-300) / <alpha-value>)",
          400: "oklch(var(--primary-400) / <alpha-value>)",
          500: "oklch(var(--primary-500) / <alpha-value>)",
          600: "oklch(var(--primary-600) / <alpha-value>)",
          700: "oklch(var(--primary-700) / <alpha-value>)",
          800: "oklch(var(--primary-800) / <alpha-value>)",
          900: "oklch(var(--primary-900) / <alpha-value>)",
          950: "oklch(var(--primary-950) / <alpha-value>)",
        },
        accent: {
          50: "oklch(var(--accent-50) / <alpha-value>)",
          100: "oklch(var(--accent-100) / <alpha-value>)",
          200: "oklch(var(--accent-200) / <alpha-value>)",
          300: "oklch(var(--accent-300) / <alpha-value>)",
          400: "oklch(var(--accent-400) / <alpha-value>)",
          500: "oklch(var(--accent-500) / <alpha-value>)",
          600: "oklch(var(--accent-600) / <alpha-value>)",
          700: "oklch(var(--accent-700) / <alpha-value>)",
          800: "oklch(var(--accent-800) / <alpha-value>)",
          900: "oklch(var(--accent-900) / <alpha-value>)",
          950: "oklch(var(--accent-950) / <alpha-value>)",
        },
        secondary: {
          50: "oklch(var(--secondary-50) / <alpha-value>)",
          100: "oklch(var(--secondary-100) / <alpha-value>)",
          200: "oklch(var(--secondary-200) / <alpha-value>)",
          300: "oklch(var(--secondary-300) / <alpha-value>)",
          400: "oklch(var(--secondary-400) / <alpha-value>)",
          500: "oklch(var(--secondary-500) / <alpha-value>)",
          600: "oklch(var(--secondary-600) / <alpha-value>)",
          700: "oklch(var(--secondary-700) / <alpha-value>)",
          800: "oklch(var(--secondary-800) / <alpha-value>)",
          900: "oklch(var(--secondary-900) / <alpha-value>)",
          950: "oklch(var(--secondary-950) / <alpha-value>)",
        },
        foreground: {
          50: "oklch(var(--foreground-50) / <alpha-value>)",
          100: "oklch(var(--foreground-100) / <alpha-value>)",
          200: "oklch(var(--foreground-200) / <alpha-value>)",
          300: "oklch(var(--foreground-300) / <alpha-value>)",
          400: "oklch(var(--foreground-400) / <alpha-value>)",
          500: "oklch(var(--foreground-500) / <alpha-value>)",
          600: "oklch(var(--foreground-600) / <alpha-value>)",
          700: "oklch(var(--foreground-700) / <alpha-value>)",
          800: "oklch(var(--foreground-800) / <alpha-value>)",
          900: "oklch(var(--foreground-900) / <alpha-value>)",
          950: "oklch(var(--foreground-950) / <alpha-value>)",
        },
      },
      animation: {
        "float-slow": "float-slow 6s ease-in-out infinite",
        "float-medium": "float-medium 4s ease-in-out infinite",
        "float-fast": "float-fast 3s ease-in-out infinite",
        "pulse-soft": "pulse-soft 3s ease-in-out infinite",
        "slide-up": "slide-up 0.6s ease-out forwards",
        "scale-in": "scale-in 0.4s ease-out forwards",
        "glow-pulse": "glow-pulse 2s ease-in-out infinite",
        "assemble": "assemble 1.5s ease-out forwards",
      },
      keyframes: {
        "float-slow": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "50%": { transform: "translateY(-12px) rotate(2deg)" },
        },
        "float-medium": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "50%": { transform: "translateY(-8px) rotate(-1deg)" },
        },
        "float-fast": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "50%": { transform: "translateY(-6px) rotate(1deg)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "0.6" },
          "50%": { opacity: "1" },
        },
        "slide-up": {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "scale-in": {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "glow-pulse": {
          "0%, 100%": { filter: "drop-shadow(0 0 8px #FF5A1F60)" },
          "50%": { filter: "drop-shadow(0 0 20px #FF5A1F)" },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;